### ISSUE TITLE
How could I use browser to see on localhost?

### ISSUE THREAD

**Issue by fiadigifrank** [ybouane/aPulse#1]
Hi I use the way on README.

1. "node", "watcher.sj "

2. "pm2 start pm2.json " 

I can saw results in my shell , but can't use browser (127.0.0.1:3000) 

So may I know how to serve with http in browser ? or something I missed? Thank you

**Comment by ybouane** [comment]
I added some instructions to the readme for serving the static files:
I'd recommend the http-server method for you:
https://github.com/ybouane/aPulse?tab=readme-ov-file#serving-the-status-page
